# Generated by Django 3.2.23 on 2024-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20240510_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteduser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
