export type OrganizationAccount = {
  id: number;
  created_at: string;
  updated_at: string;
  description: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  private_cost: number;
  idle_gas_usage: number;
  distance_gas_usage: number;
  auto_update_interval_for_maps: number;
  drivers_assigned_to_devices: boolean;
  enable_map_clustering: string;
  open_reports_in_new_tab: boolean;
  sync_driver_id_from_driver_admin: boolean;
  has_snowplows: boolean;
  hide_total_rows_in_csv: boolean;
  timezone: string | null;
  speed_units: string;
  distance_units: string;
  volume_units: string;
  economy_units: string;
  pressure_units: string;
  temperature_units: string;
  lat_lan_format: string;
  route_segment_color_rule: string | null;
  route_line_thickness: string;
  multi_vehicle_map_name: string | null;
  device_title: string | null;
  device_title_plural: string | null;
  device_group_title: string | null;
  device_group_title_plural: string | null;
  address_title: string | null;
  address_title_plural: string | null;
  default_login_user_id: string | null;
  default_overlay: string | null;
  maintenance_intervals: {
    last_maintenance_1: number;
    last_maintenance_2: number;
    last_maintenance_3: number;
    last_maintenance_4: number;
    last_maintenance_5: number;
    last_maintenance_6: number;
    last_maintenance_7: number;
    last_maintenance_8: number;
    last_maintenance_9: number;
    last_maintenance_10: number;
    last_service_time_1: number;
    last_service_time_2: number;
    last_service_time_3: number;
    last_service_time_4: number;
    last_service_time_5: number;
    last_eng_hours_maintenance_1: number;
    last_eng_hours_maintenance_2: number;
    last_eng_hours_maintenance_3: number;
    last_eng_hours_maintenance_4: number;
    last_eng_hours_maintenance_5: number;
  };
  harsh_braking: string | null;
  harsh_acceleration: string | null;
  speeding: string | null;
  reverse: string | null;
  seatbelt_off: string | null;
  harsh_cornering: string | null;
  idle_ratio: string | null;
  impact_crash_ai: string | null;
  cellphone_use_ai: string | null;
  distracted_driving_ai: string | null;
  drinking_eating_ai: string | null;
  smoking_ai: string | null;
  possible_fatigue_ai: string | null;
  obstructed_camera_ai: string | null;
  tailgating_ai: string | null;
};
