# Generated by Django 3.2.23 on 2024-05-27 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0005_alter_group_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_alter_inviteduser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_id', models.CharField(max_length=255, unique=True)),
                ('zone_type', models.CharField(choices=[('Circle', 'Circle'), ('Polygon', 'Polygon'), ('Route', 'Route')], default='Circle', max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geocode', models.TextField(blank=True, null=True)),
                ('lat_lng', models.CharField(blank=True, max_length=255, null=True)),
                ('overlap_priority', models.CharField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=0, max_length=255, null=True)),
                ('reverse_geocode', models.BooleanField(default=False)),
                ('arrival_geozone', models.BooleanField(default=False)),
                ('departure_zone', models.BooleanField(default=False)),
                ('zone_color', models.CharField(blank=True, choices=[('Default', 'Default'), ('Black', 'Black'), ('Brown', 'Brown'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Gray', 'Gray'), ('White', 'White'), ('Cyan', 'Cyan'), ('Pink', 'Pink')], default='Default', max_length=20, null=True)),
                ('speed_limit', models.FloatField(blank=True, help_text='Speed limit in Miles', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geozone', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='geozone', to='group.Group')),
                ('organization', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geozone', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Geozone',
                'verbose_name_plural': 'Geozones',
            },
        ),
    ]
