
export const TIMEZONE_OPTIONS = [
  {"id": "US_HAWAII", "value": "US/Hawaii", "label": "US/Hawaii"},
  {"id": "US_ALASKA", "value": "US/Alaska", "label": "US/Alaska"},
  {"id": "US_PACIFIC", "value": "US/Pacific", "label": "US/Pacific"},
  {"id": "US_ARIZONA", "value": "US/Arizona", "label": "US/Arizona"},
  {"id": "US_MOUNTAIN", "value": "US/Mountain", "label": "US/Mountain"},
  {"id": "US_CENTERAL", "value": "US/Central", "label": "US/Central"},
  {"id": "US_EASTERN", "value": "US/Eastern", "label": "US/Eastern"},
  {"id": "CANADA_PACIFIC", "value": "Canada/Pacific", "label": "Canada/Pacific"},
  {"id": "CANADA_MOUNTAIN", "value": "Canada/Mountain", "label": "Canada/Mountain"},
  {"id": "CANADA_CENTERAL", "value": "Canada/Central", "label": "Canada/Central"},
  {"id": "CANADA_EASTERN", "value": "Canada/Eastern", "label": "Canada/Eastern"},
  {"id": "CANADA_ATLANTIC", "value": "Canada/Atlantic", "label": "Canada/Atlantic"},
  {"id": "MEXICO_BAJA_NORTE", "value": "Mexico/BajaNorte", "label": "Mexico/BajaNorte"},
  {"id": "MEXICO_BAJASUR", "value": "Mexico/BajaSur", "label": "Mexico/BajaSur"},
  {"id": "MEXICO_GENERAL", "value": "Mexico/General", "label": "Mexico/General"},
  {"id": "EUROPE_ATHENS", "value": "Europe/Athens", "label": "Europe/Athens"},
  {"id": "EUROPE_BERLIN", "value": "Europe/Berlin", "label": "Europe/Berlin"},
  {"id": "EUROPE_DUBLIN", "value": "Europe/Dublin", "label": "Europe/Dublin"},
  {"id": "EUROPE_HELINSKI", "value": "Europe/Helsinki", "label": "Europe/Helsinki"},
  {"id": "EUROPE_KEIV", "value": "Europe/Kiev", "label": "Europe/Kiev"},
  {"id": "EUROPE_LISBON", "value": "Europe/Lisbon", "label": "Europe/Lisbon"},
  {"id": "EUROPE_LONDON", "value": "Europe/London", "label": "Europe/London"},
  {"id": "EUROPE_MADRID", "value": "Europe/Madrid", "label": "Europe/Madrid"},
  {"id": "EUROPE_MOSCOW", "value": "Europe/Moscow", "label": "Europe/Moscow"},
  {"id": "EUROPE_OSLO", "value": "Europe/Oslo", "label": "Europe/Oslo"},
  {"id": "EUROPE_PARIS", "value": "Europe/Paris", "label": "Europe/Paris"},
  {"id": "EUROPE_ROME", "value": "Europe/Rome", "label": "Europe/Rome"},
  {"id": "EUROPE_STOCKHOLM", "value": "Europe/Stockholm", "label": "Europe/Stockholm"},
  {"id": "EUROPE_ZURICH", "value": "Europe/Zurich", "label": "Europe/Zurich"},
  {"id": "PACIFIC_AUCKLAND", "value": "Pacific/Auckland", "label": "Pacific/Auckland"},
  {"id": "PACIFIC_CHATHAM", "value": "Pacific/Chatham", "label": "Pacific/Chatham"},
  {"id": "GMT", "value": "GMT", "label": "GMT"},
  {"id": "GMT_00_00", "value": "GMT+00:00", "label": "GMT+00:00"},
  {"id": "GMT_01_00", "value": "GMT+01:00", "label": "GMT+01:00"},
  {"id": "GMT_02_00", "value": "GMT+02:00", "label": "GMT+02:00"},
  {"id": "GMT_03_00", "value": "GMT+03:00", "label": "GMT+03:00"},
  {"id": "GMT_04_00", "value": "GMT+04:00", "label": "GMT+04:00"},
  {"id": "GMT_05_00", "value": "GMT+05:00", "label": "GMT+05:00"},
  {"id": "GMT_06_00", "value": "GMT+06:00", "label": "GMT+06:00"},
  {"id": "GMT_07_00", "value": "GMT+07:00", "label": "GMT+07:00"},
  {"id": "GMT_08_00", "value": "GMT+08:00", "label": "GMT+08:00"},
  {"id": "GMT_09_00", "value": "GMT+09:00", "label": "GMT+09:00"},
  {"id": "GMT_10_00", "value": "GMT+10:00", "label": "GMT+10:00"},
  {"id": "GMT_11_00", "value": "GMT+11:00", "label": "GMT+11:00"},
  {"id": "GMT_12_00", "value": "GMT+12:00", "label": "GMT+12:00"},
  {"id": "GMT_13_00", "value": "GMT+13:00", "label": "GMT+13:00"},
  {"id": "GMT_14_00", "value": "GMT+14:00", "label": "GMT+14:00"},
  {"id": "GMT_N_01_00", "value": "GMT-01:00", "label": "GMT-01:00"},
  {"id": "GMT_N_02_00", "value": "GMT-02:00", "label": "GMT-02:00"},
  {"id": "GMT_N_03_00", "value": "GMT-03:00", "label": "GMT-03:00"},
  {"id": "GMT_N_04_00", "value": "GMT-04:00", "label": "GMT-04:00"},
  {"id": "GMT_N_05_00", "value": "GMT-05:00", "label": "GMT-05:00"},
  {"id": "GMT_N_06_00", "value": "GMT-06:00", "label": "GMT-06:00"},
  {"id": "GMT_N_07_00", "value": "GMT-07:00", "label": "GMT-07:00"},
  {"id": "GMT_N_08_00", "value": "GMT-08:00", "label": "GMT-08:00"},
  {"id": "GMT_N_09_00", "value": "GMT-09:00", "label": "GMT-09:00"},
  {"id": "GMT_N_10_00", "value": "GMT-10:00", "label": "GMT-10:00"},
  {"id": "GMT_N_11_00", "value": "GMT-11:00", "label": "GMT-11:00"},
  {"id": "GMT_N_12_00", "value": "GMT-12:00", "label": "GMT-12:00"}
]

export const DEFAULT_OVERLAY_OPTIONS = [
  {"id": "UNSPECIFIED", "value": "Unspecified", "label": "Unspecified"},
  {"id": "SOONERSALOONWHITE", "value": "SoonerSaloonWhite", "label": "SoonerSaloonWhite"},
  {"id": "SOONERSALOONTRANSPARENT", "value": "SoonerSaloonTransparent", "label": "SoonerSaloonTransparent"},
  {"id": "VIRGINIA", "value": "Virginia", "label": "Virginia"},
  {"id": "CLEVELANDPOLICEDISTRICT_1", "value": "ClevelandPoliceDistrict1", "label": "ClevelandPoliceDistrict1"},
  {"id": "CLEVELANDPOLICEDISTRICT_2", "value": "ClevelandPoliceDistrict2", "label": "ClevelandPoliceDistrict2"},
  {"id": "CLEVELANDPOLICEDISTRICT_3", "value": "ClevelandPoliceDistrict3", "label": "ClevelandPoliceDistrict3"},
  {"id": "CLEVELANDPOLICEDISTRICT_4", "value": "ClevelandPoliceDistrict4", "label": "ClevelandPoliceDistrict4"},
  {"id": "CLEVELANDPOLICEDISTRICT_5", "value": "ClevelandPoliceDistrict5", "label": "ClevelandPoliceDistrict5"},
  {"id": "CLEVELANDWARD_1", "value": "ClevelandWard1", "label": "ClevelandWard1"},
  {"id": "CLEVELANDWARD_2", "value": "ClevelandWard2", "label": "ClevelandWard2"},
  {"id": "CLEVELANDWARD_3", "value": "ClevelandWard3", "label": "ClevelandWard3"},
  {"id": "CLEVELANDWARD_4", "value": "ClevelandWard4", "label": "ClevelandWard4"},
  {"id": "CLEVELANDWARD_5", "value": "ClevelandWard5", "label": "ClevelandWard5"},
  {"id": "CLEVELANDWARD_6", "value": "ClevelandWard6", "label": "ClevelandWard6"},
  {"id": "CLEVELANDWARD_7", "value": "ClevelandWard7", "label": "ClevelandWard7"},
  {"id": "CLEVELANDWARD_8", "value": "ClevelandWard8", "label": "ClevelandWard8"},
  {"id": "CLEVELANDWARD_9", "value": "ClevelandWard9", "label": "ClevelandWard9"},
  {"id": "CLEVELANDWARD_10", "value": "ClevelandWard10", "label": "ClevelandWard10"},
  {"id": "CLEVELANDWARD_11", "value": "ClevelandWard11", "label": "ClevelandWard11"},
  {"id": "CLEVELANDWARD_12", "value": "ClevelandWard12", "label": "ClevelandWard12"},
  {"id": "CLEVELANDWARD_13", "value": "ClevelandWard13", "label": "ClevelandWard13"},
  {"id": "CLEVELANDWARD_14", "value": "ClevelandWard14", "label": "ClevelandWard14"},
  {"id": "CLEVELANDWARD_15", "value": "ClevelandWard15", "label": "ClevelandWard15"},
  {"id": "CLEVELANDWARD_16", "value": "ClevelandWard16", "label": "ClevelandWard16"},
  {"id": "CLEVELANDWARD_17", "value": "ClevelandWard17", "label": "ClevelandWard17"},
  {"id": "CLEVELANDWARD_18", "value": "ClevelandWard18", "label": "ClevelandWard18"},
  {"id": "CLEVELANDWARD_19", "value": "ClevelandWard19", "label": "ClevelandWard19"}
]

export const USER_STATE_OPTIONS = [
  {"id": "LOCKED", "value": "Locked", "label": "Locked"},
  {"id": "UNLOCKED", "value": "Unlocked", "label": "Unlocked"}
]

export const FIRST_LOGIN_PAGE_OPTIONS = [
  {"id": "MAIN_MENU", "value": "Main Menu", "label": "Main Menu"},
  {"id": "DEVICE_MAP", "value": "Device Map", "label": "Device Map"},
  {"id": "DASHBOARD", "value": "Dashboard", "label": "Dashboard"},
  {"id": "FLEET_MAP", "value": "Fleet Map", "label": "Fleet Map"},
  {"id": "DETAIL_REPORTS", "value": "Detail Reports", "label": "Detail Reports"},
  {"id": "FLEET_REPORTS", "value": "Fleet Reports", "label": "Fleet Reports"}
]