# Generated by Django 3.2.23 on 2024-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_tag_id', models.CharField(max_length=255, unique=True)),
                ('fleet_tag_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('last_event_code', models.CharField(blank=True, max_length=255, null=True)),
                ('in_range', models.BooleanField(default=False)),
                ('in_range_device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_address', models.TextField(blank=True, null=True)),
                ('last_altitude', models.FloatField(blank=True, help_text='Altitude in feet', null=True)),
                ('distance_traveled', models.FloatField(blank=True, help_text='Distance traveled in miles', null=True)),
                ('tag_signal_strength', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_battery_level', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Fahrenheit', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
