# Generated by Django 3.2.23 on 2024-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleettag',
            name='fleet_tag_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fleettag',
            name='fleet_tag_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
