# Generated by Django 3.2.23 on 2024-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_tag', '0002_auto_20240523_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleettag',
            name='fleet_tag_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
