# Generated by Django 3.2.23 on 2024-05-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_inviteduser_username'),
        ('group', '0004_auto_20240515_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.organization'),
        ),
    ]
