# Generated by Django 3.2.23 on 2024-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20240513_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
