# Generated by Django 3.2.23 on 2024-05-14 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0004_vehicle_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAndDriverMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver_mapping', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle_mapping', to='driver.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver_mapping', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle and Driver Mapping',
                'verbose_name_plural': 'Vehicles and Drivers Mapping',
            },
        ),
    ]
