# Generated by Django 3.2.23 on 2024-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicleanddrivermapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleAndDriverMapping',
        ),
    ]
