# Generated by Django 3.2.23 on 2024-05-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_delete_vehicleanddrivermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='asset_type',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('Ambulance', 'Ambulance'), ('Armored Truck', 'Armored Truck'), ('Box Truck', 'Box Truck'), ('Bucket Truck', 'Bucket Truck'), ('Cable Puller', 'Cable Puller'), ('Car', 'Car'), ('Car Carrier', 'Car Carrier'), ('Clip Truck', 'Clip Truck'), ('Container', 'Container'), ('Dump Truck', 'Dump Truck'), ('Electric Vehicle', 'Electric Vehicle'), ('Fire Engine', 'Fire Engine'), ('Flatbed', 'Flatbed'), ('Gang Truck', 'Gang Truck'), ('Heavy Truck', 'Heavy Truck'), ('Light Truck', 'Licght Truck'), ('Line Truck', 'Line Truck'), ('Mobile Wash', 'Mobile Wash'), ('Pickup with Plow', 'Pickup With Plow'), ('Pick Up', 'Pick Up'), ('Rack Truck', 'Rack Truck'), ('Rack with Boom', 'Rack With Boom'), ('Railcar', 'Railcar'), ('Reefer', 'Reefer'), ('Road Truck', 'Road Truck'), ('Rodder Truck', 'Rodder Truck'), ('Roll Off', 'Roll Off'), ('Scissor Lift', 'Scissor Lift'), ('Sedan', 'Sedan'), ('Sewer Truck', 'Sewer Truck'), ('Snow Fighter', 'Snow Fighter'), ('Snow Plow', 'Snow Plow'), ('Step Van', 'Step Van'), ('SUV', 'Suv'), ('SUV with Plow', 'Suv With Plow'), ('Tanker', 'Tanker'), ('Tow Boat', 'Tow Boat'), ('Tow Truck', 'Tow Truck'), ('Trailer', 'Trailer'), ('Tractor', 'Tractor'), ('Truck', 'Truck'), ('Utility Truck', 'Utility Truck'), ('Vac Truck', 'Vac Truck'), ('Van', 'Van'), ('Vehicle', 'Vehicle'), ('Welding Truck', 'Welding Truck'), ('Other', 'Other')], default='Unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='equipment_status',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('In Service', 'In Service'), ('Rented', 'Rented'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Repair', 'Repair'), ('Retired', 'Retired'), ('Spare', 'Spare')], default='Unspecified', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Unleaded', 'Unleaded'), ('Diesel', 'Diesel'), ('Leaded', 'Leaded'), ('Ethanol', 'Ethanol'), ('Methanol', 'Methanol'), ('Biodiesel', 'Biodiesel'), ('Kerosene', 'Kerosene'), ('LPG', 'Lpg'), ('Propane', 'Propane'), ('Butane', 'Butane'), ('CNG', 'Cng'), ('Methane', 'Methane'), ('Hydrogen', 'Hydrogen'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ignition_input',
            field=models.CharField(choices=[('N/A', 'N A'), ('IgnitionOn/Off', 'Ignition On Off'), ('Start/Stop', 'Start Stop'), ('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='map_route_color',
            field=models.CharField(choices=[('Default', 'Default'), ('Black', 'Black'), ('Brown', 'Brown'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Gray', 'Gray'), ('Cyan', 'Cyan'), ('Pink', 'Pink'), ('None', 'None')], default='Default', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='recorder_on',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Yes', 'Yes'), ('No', 'No')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='recorder_type',
            field=models.CharField(choices=[('None', 'None'), ('SmartWitness', 'Smartwitness'), ('Surfsight', 'Surfsight')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(choices=[('Unspecified', 'Unspecified'), ('C', 'C'), ('CDL_A', 'Cdl A'), ('CDL_B', 'Cdl B'), ('CDL_C', 'Cdl C'), ('D', 'D'), ('D_CONDITIONAL', 'D Conditional'), ('D_RESTRICED', 'D Restriced'), ('E', 'E'), ('G', 'G'), ('N/A', 'N A'), ('PERMIT', 'Permit'), ('T', 'T'), ('V', 'V')], default='Unspecified', max_length=20),
        ),
    ]
