# Generated by Django 3.2.23 on 2024-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20240516_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_display_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
