# Generated by Django 3.2.23 on 2024-05-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehicle_vehicle_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='all_vehicles',
            field=models.BooleanField(default=False),
        ),
    ]
