# Generated by Django 3.2.23 on 2024-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicle_all_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
