import * as Yup from "yup";

export const vehicleDetailFormInitialValues = {
  vehicle_id: "",
  creation_date: "",
  server_id: "",
  firmware_version: "",
  unique_id: "",
  previous_unique_id: "",
  unique_id_last_change: "",
  is_active: "",
  vehicle_description: "",
  short_name: "",
  vin: "",
  vehicle_make: "",
  vehicle_model: "",
  license_plate: "",
  license_expiration: "",
  equipment_type: "",
  equipment_status: "",
  asset_type: "",
  vehicle_class: "",
  imei_number: "",
  serial_number: "",
  country_code: "",
  phone_number: "",
  email: "",
  group_pushpin_id: "",
  map_route_color: "",
  ignition_input: "",
  maximum_speed: "",
  driver_name: "",
  driver_country_code: "",
  driver_phone_number: "",
  driver_id: "",
  fuel_type: "",
  fuel_capacity: "",
  fuel_economy: "",
  fuel_cost: "",
}

export const vehicleGroupMembershipFormInitialValues = {
  all_vehicles: "",
  demo_map: "",
  district1: "",
  district2: "",
  district3: "",
  district4: "",
  district5: "",
  district6: "",
  district7: "",
  district8: "",
  group_a: "",
  group_b: "",
  hybrid_vehicle: "",
  jacob: "",
  k9_units: "",
  map_demo: "",
  medium_group: "",
  meitrack: "",
  patrol_cars: "",
  public_works_pickups: "",
  small_group: "",
  snow_plows: "",
}

export const detailFormValidationSchema = Yup.object().shape({});

export const groupMembershipFormValidationSchema = Yup.object().shape({});