# Generated by Django 3.2.23 on 2024-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_group_organization'),
        ('users', '0002_auto_20240508_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='group.Group'),
        ),
    ]
