# Generated by Django 3.2.23 on 2024-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_overlay',
            field=models.CharField(blank=True, choices=[('Unspecified', 'Unspecified'), ('SoonerSaloonWhite', 'Soonersaloonwhite'), ('SoonerSaloonTransparent', 'Soonersaloontransparent'), ('Virginia', 'Virginia'), ('ClevelandPoliceDistrict1', 'Clevelandpolicedistrict 1'), ('ClevelandPoliceDistrict2', 'Clevelandpolicedistrict 2'), ('ClevelandPoliceDistrict3', 'Clevelandpolicedistrict 3'), ('ClevelandPoliceDistrict4', 'Clevelandpolicedistrict 4'), ('ClevelandPoliceDistrict5', 'Clevelandpolicedistrict 5'), ('ClevelandWard1', 'Clevelandward 1'), ('ClevelandWard2', 'Clevelandward 2'), ('ClevelandWard3', 'Clevelandward 3'), ('ClevelandWard4', 'Clevelandward 4'), ('ClevelandWard5', 'Clevelandward 5'), ('ClevelandWard6', 'Clevelandward 6'), ('ClevelandWard7', 'Clevelandward 7'), ('ClevelandWard8', 'Clevelandward 8'), ('ClevelandWard9', 'Clevelandward 9'), ('ClevelandWard10', 'Clevelandward 10'), ('ClevelandWard11', 'Clevelandward 11'), ('ClevelandWard12', 'Clevelandward 12'), ('ClevelandWard13', 'Clevelandward 13'), ('ClevelandWard14', 'Clevelandward 14'), ('ClevelandWard15', 'Clevelandward 15'), ('ClevelandWard16', 'Clevelandward 16'), ('ClevelandWard17', 'Clevelandward 17'), ('ClevelandWard18', 'Clevelandward 18'), ('ClevelandWard19', 'Clevelandward 19')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_login_page',
            field=models.CharField(blank=True, choices=[('Main Menu', 'Main Menu'), ('Device Map', 'Device Map'), ('Dashboard', 'Dashboard'), ('Fleet Map', 'Fleet Map'), ('Detail Reports', 'Detail Reports'), ('Fleet Reports', 'Fleet Reports')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, choices=[('US/Hawaii', 'Us Hawaii'), ('US/Alaska', 'Us Alaska'), ('US/Pacific', 'Us Pacific'), ('US/Arizona', 'Us Arizona'), ('US/Mountain', 'Us Mountain'), ('US/Central', 'Us Centeral'), ('US/Eastern', 'Us Eastern'), ('Canada/Pacific', 'Canada Pacific'), ('Canada/Mountain', 'Canada Mountain'), ('Canada/Central', 'Canada Centeral'), ('Canada/Eastern', 'Canada Eastern'), ('Canada/Atlantic', 'Canada Atlantic'), ('Mexico/BajaNorte', 'Mexico Baja Norte'), ('Mexico/BajaSur', 'Mexico Bajasur'), ('Mexico/General', 'Mexico General'), ('Europe/Athens', 'Europe Athens'), ('Europe/Berlin', 'Europe Berlin'), ('Europe/Dublin', 'Europe Dublin'), ('Europe/Helsinki', 'Europe Helinski'), ('Europe/Kiev', 'Europe Keiv'), ('Europe/Lisbon', 'Europe Lisbon'), ('Europe/London', 'Europe London'), ('Europe/Madrid', 'Europe Madrid'), ('Europe/Moscow', 'Europe Moscow'), ('Europe/Oslo', 'Europe Oslo'), ('Europe/Paris', 'Europe Paris'), ('Europe/Rome', 'Europe Rome'), ('Europe/Stockholm', 'Europe Stockholm'), ('Europe/Zurich', 'Europe Zurich'), ('Pacific/Auckland', 'Pacific Auckland'), ('Pacific/Chatham', 'Pacific Chatham'), ('GMT', 'Gmt'), ('GMT+00:00', 'Gmt 00 00'), ('GMT+01:00', 'Gmt 01 00'), ('GMT+02:00', 'Gmt 02 00'), ('GMT+03:00', 'Gmt 03 00'), ('GMT+04:00', 'Gmt 04 00'), ('GMT+05:00', 'Gmt 05 00'), ('GMT+06:00', 'Gmt 06 00'), ('GMT+07:00', 'Gmt 07 00'), ('GMT+08:00', 'Gmt 08 00'), ('GMT+09:00', 'Gmt 09 00'), ('GMT+10:00', 'Gmt 10 00'), ('GMT+11:00', 'Gmt 11 00'), ('GMT+12:00', 'Gmt 12 00'), ('GMT+13:00', 'Gmt 13 00'), ('GMT+14:00', 'Gmt 14 00'), ('GMT-01:00', 'Gmt N 01 00'), ('GMT-02:00', 'Gmt N 02 00'), ('GMT-03:00', 'Gmt N 03 00'), ('GMT-04:00', 'Gmt N 04 00'), ('GMT-05:00', 'Gmt N 05 00'), ('GMT-06:00', 'Gmt N 06 00'), ('GMT-07:00', 'Gmt N 07 00'), ('GMT-08:00', 'Gmt N 08 00'), ('GMT-09:00', 'Gmt N 09 00'), ('GMT-10:00', 'Gmt N 10 00'), ('GMT-11:00', 'Gmt N 11 00'), ('GMT-12:00', 'Gmt N 12 00')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_state',
            field=models.CharField(blank=True, choices=[('Locked', 'Locked'), ('Unlocked', 'Unlocked')], default=None, max_length=20, null=True),
        ),
    ]
