# Generated by Django 3.2.23 on 2024-05-20 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240516_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('private_cost', models.FloatField(blank=True, default=0.0, null=True)),
                ('idle_gas_usage', models.FloatField(blank=True, default=0.0, null=True)),
                ('distance_gas_usage', models.FloatField(blank=True, default=0.0, null=True)),
                ('auto_update_interval_for_maps', models.IntegerField(blank=True, help_text='In seconds', null=True)),
                ('drivers_assigned_to_devices', models.BooleanField(default=False)),
                ('enable_map_clustering', models.CharField(blank=True, choices=[('Off', 'Off'), ('On', 'On'), ('Always show all pushpins', 'Always')], default='Off', max_length=40, null=True)),
                ('open_reports_in_new_tab', models.BooleanField(default=False)),
                ('sync_driver_id_from_driver_admin', models.BooleanField(default=False)),
                ('has_snowplows', models.BooleanField(default=False)),
                ('hide_total_rows_in_csv', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, choices=[('US/Hawaii', 'Us Hawaii'), ('US/Alaska', 'Us Alaska'), ('US/Pacific', 'Us Pacific'), ('US/Arizona', 'Us Arizona'), ('US/Mountain', 'Us Mountain'), ('US/Central', 'Us Centeral'), ('US/Eastern', 'Us Eastern'), ('Canada/Pacific', 'Canada Pacific'), ('Canada/Mountain', 'Canada Mountain'), ('Canada/Central', 'Canada Centeral'), ('Canada/Eastern', 'Canada Eastern'), ('Canada/Atlantic', 'Canada Atlantic'), ('Mexico/BajaNorte', 'Mexico Baja Norte'), ('Mexico/BajaSur', 'Mexico Bajasur'), ('Mexico/General', 'Mexico General'), ('Europe/Athens', 'Europe Athens'), ('Europe/Berlin', 'Europe Berlin'), ('Europe/Dublin', 'Europe Dublin'), ('Europe/Helsinki', 'Europe Helinski'), ('Europe/Kiev', 'Europe Keiv'), ('Europe/Lisbon', 'Europe Lisbon'), ('Europe/London', 'Europe London'), ('Europe/Madrid', 'Europe Madrid'), ('Europe/Moscow', 'Europe Moscow'), ('Europe/Oslo', 'Europe Oslo'), ('Europe/Paris', 'Europe Paris'), ('Europe/Rome', 'Europe Rome'), ('Europe/Stockholm', 'Europe Stockholm'), ('Europe/Zurich', 'Europe Zurich'), ('Pacific/Auckland', 'Pacific Auckland'), ('Pacific/Chatham', 'Pacific Chatham'), ('GMT', 'Gmt'), ('GMT+00:00', 'Gmt 00 00'), ('GMT+01:00', 'Gmt 01 00'), ('GMT+02:00', 'Gmt 02 00'), ('GMT+03:00', 'Gmt 03 00'), ('GMT+04:00', 'Gmt 04 00'), ('GMT+05:00', 'Gmt 05 00'), ('GMT+06:00', 'Gmt 06 00'), ('GMT+07:00', 'Gmt 07 00'), ('GMT+08:00', 'Gmt 08 00'), ('GMT+09:00', 'Gmt 09 00'), ('GMT+10:00', 'Gmt 10 00'), ('GMT+11:00', 'Gmt 11 00'), ('GMT+12:00', 'Gmt 12 00'), ('GMT+13:00', 'Gmt 13 00'), ('GMT+14:00', 'Gmt 14 00'), ('GMT-01:00', 'Gmt N 01 00'), ('GMT-02:00', 'Gmt N 02 00'), ('GMT-03:00', 'Gmt N 03 00'), ('GMT-04:00', 'Gmt N 04 00'), ('GMT-05:00', 'Gmt N 05 00'), ('GMT-06:00', 'Gmt N 06 00'), ('GMT-07:00', 'Gmt N 07 00'), ('GMT-08:00', 'Gmt N 08 00'), ('GMT-09:00', 'Gmt N 09 00'), ('GMT-10:00', 'Gmt N 10 00'), ('GMT-11:00', 'Gmt N 11 00'), ('GMT-12:00', 'Gmt N 12 00')], default=None, max_length=20, null=True)),
                ('speed_units', models.CharField(blank=True, choices=[('Mph', 'Mph'), ('Km/h', 'Kmh'), ('Knots', 'Knots')], default='Mph', max_length=20, null=True)),
                ('distance_units', models.CharField(blank=True, choices=[('Miles', 'Miles'), ('Km', 'Km'), ('Nautical Miles', 'Nautical Miles')], default='Miles', max_length=20, null=True)),
                ('volume_units', models.CharField(blank=True, choices=[('Gallons', 'Gallons'), ('Liters', 'Liters'), ('Imperial Gallons', 'Imperial Gallons'), ('Ft^3', 'Ft 3')], default='Gallons', max_length=20, null=True)),
                ('economy_units', models.CharField(blank=True, choices=[('Mpg', 'Mpg'), ('Km/l', 'Kml'), ('Kpg', 'Kpg'), ('L/100km', 'L 100Km')], default='Mpg', max_length=20, null=True)),
                ('pressure_units', models.CharField(blank=True, choices=[('kPa', 'Kpa'), ('psi', 'Psi'), ('mmHg', 'Mmhg'), ('bar', 'Bar')], default='kPa', max_length=20, null=True)),
                ('temperature_units', models.CharField(blank=True, choices=[('Celsius', 'Celsius'), ('Fahrenheit', 'Fahrenheit')], default='Fahrenheit', max_length=20, null=True)),
                ('lat_lan_format', models.CharField(blank=True, choices=[('Degrees', 'Degrees'), ('Deg:Min:Sec', 'Deg Min Sec'), ('Deg:Min', 'Deg Min')], default='Degrees', max_length=20, null=True)),
                ('route_segment_color_rule', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('route_line_thickness', models.IntegerField(blank=True, choices=[('1 (Thinnest)', 'One'), ('2 (Default)', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8 (Widest)', 'Eight')], default='2 (Default)', max_length=20, null=True)),
                ('device_title', models.CharField(blank=True, max_length=255, null=True)),
                ('device_title_plural', models.CharField(blank=True, max_length=255, null=True)),
                ('device_group_title', models.CharField(blank=True, max_length=255, null=True)),
                ('device_group_title_plural', models.CharField(blank=True, max_length=255, null=True)),
                ('address_title', models.CharField(blank=True, max_length=255, null=True)),
                ('address_title_plural', models.CharField(blank=True, max_length=255, null=True)),
                ('default_login_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('default_overlay', models.CharField(blank=True, choices=[('Unspecified', 'Unspecified'), ('SoonerSaloonWhite', 'Soonersaloonwhite'), ('SoonerSaloonTransparent', 'Soonersaloontransparent'), ('Virginia', 'Virginia'), ('ClevelandPoliceDistrict1', 'Clevelandpolicedistrict 1'), ('ClevelandPoliceDistrict2', 'Clevelandpolicedistrict 2'), ('ClevelandPoliceDistrict3', 'Clevelandpolicedistrict 3'), ('ClevelandPoliceDistrict4', 'Clevelandpolicedistrict 4'), ('ClevelandPoliceDistrict5', 'Clevelandpolicedistrict 5'), ('ClevelandWard1', 'Clevelandward 1'), ('ClevelandWard2', 'Clevelandward 2'), ('ClevelandWard3', 'Clevelandward 3'), ('ClevelandWard4', 'Clevelandward 4'), ('ClevelandWard5', 'Clevelandward 5'), ('ClevelandWard6', 'Clevelandward 6'), ('ClevelandWard7', 'Clevelandward 7'), ('ClevelandWard8', 'Clevelandward 8'), ('ClevelandWard9', 'Clevelandward 9'), ('ClevelandWard10', 'Clevelandward 10'), ('ClevelandWard11', 'Clevelandward 11'), ('ClevelandWard12', 'Clevelandward 12'), ('ClevelandWard13', 'Clevelandward 13'), ('ClevelandWard14', 'Clevelandward 14'), ('ClevelandWard15', 'Clevelandward 15'), ('ClevelandWard16', 'Clevelandward 16'), ('ClevelandWard17', 'Clevelandward 17'), ('ClevelandWard18', 'Clevelandward 18'), ('ClevelandWard19', 'Clevelandward 19')], default=None, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
