# Generated by Django 3.2.23 on 2024-05-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='route_line_thickness',
            field=models.CharField(blank=True, choices=[('1 (Thinnest)', 'One'), ('2 (Default)', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8 (Widest)', 'Eight')], default='2 (Default)', max_length=20, null=True),
        ),
    ]
