# Generated by Django 3.2.23 on 2024-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_route_line_thickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='multi_vehicle_map_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
