# Generated by Django 3.2.23 on 2024-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_multi_vehicle_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cellphone_use_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='distracted_driving_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='harsh_acceleration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='harsh_braking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='harsh_cornering',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='idle_ratio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='impact_crash_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='maintenance_intervals',
            field=models.JSONField(blank=True, default={'last_eng_hours_maintenance_1': 0, 'last_eng_hours_maintenance_2': 0, 'last_eng_hours_maintenance_3': 0, 'last_eng_hours_maintenance_4': 0, 'last_eng_hours_maintenance_5': 0, 'last_maintenance_1': 0, 'last_maintenance_10': 0, 'last_maintenance_2': 0, 'last_maintenance_3': 0, 'last_maintenance_4': 0, 'last_maintenance_5': 0, 'last_maintenance_6': 0, 'last_maintenance_7': 0, 'last_maintenance_8': 0, 'last_maintenance_9': 0, 'last_service_time_1': 0, 'last_service_time_2': 0, 'last_service_time_3': 0, 'last_service_time_4': 0, 'last_service_time_5': 0}, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='obstructed_camera_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='possible_fatigue_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reverse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='seatbelt_off',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='smoking_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='speeding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
