# Generated by Django 3.2.23 on 2024-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240521_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='drinking_eating_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='tailgating_ai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
