# Generated by Django 3.2.23 on 2024-05-13 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0003_alter_vehicle_vehicle_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('badge_employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('licence_type', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_state', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=255, null=True)),
                ('licence_expiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('licence_status', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_card_no', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_card_expiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_hazmat_certified', models.BooleanField(default=False)),
                ('twic', models.CharField(blank=True, max_length=255, null=True)),
                ('twic_expiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_drivers', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
