# Generated by Django 3.2.23 on 2024-05-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
    ]
