# Generated by Django 3.2.23 on 2024-05-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_delete_vehicleanddrivermapping'),
        ('driver', '0003_remove_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='vehicle.vehicle'),
        ),
    ]
