# Generated by Django 3.2.23 on 2024-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_vehicle_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='licence_state',
            field=models.CharField(choices=[('AL', 'Al'), ('AK', 'Ak'), ('AZ', 'Az'), ('AR', 'Ar'), ('CA', 'Ca'), ('CO', 'Co'), ('CT', 'Ct'), ('DE', 'De'), ('DC', 'Dc'), ('FL', 'Fl'), ('GA', 'Ga'), ('HI', 'Hi'), ('ID', 'Id'), ('IL', 'Il'), ('IN', 'In'), ('IA', 'Ia'), ('KS', 'Ks'), ('KY', 'Ky'), ('LA', 'La'), ('ME', 'Me'), ('MD', 'Md'), ('MA', 'Ma'), ('MI', 'Mi'), ('MN', 'Mn'), ('MS', 'Ms'), ('MO', 'Mo'), ('MT', 'Mt'), ('NE', 'Ne'), ('NV', 'Nv'), ('NH', 'Nh'), ('NJ', 'Nj'), ('NM', 'Nm'), ('NY', 'Ny'), ('NC', 'Nc'), ('ND', 'Nd'), ('OH', 'Oh'), ('OK', 'Ok'), ('OR', 'Or'), ('PA', 'Pa'), ('RI', 'Ri'), ('SC', 'Sc'), ('SD', 'Sd'), ('TN', 'Tn'), ('TX', 'Tx'), ('UT', 'Ut'), ('VT', 'Vt'), ('VA', 'Va'), ('WA', 'Wa'), ('WV', 'Wv'), ('WI', 'Wi'), ('WY', 'Wy')], default='AL', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licence_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('SUSPENDED', 'Suspended'), ('SURRENDERED', 'Surrendered'), ('REVOKED', 'Revoked'), ('RESTRICTED', 'Restricted'), ('PERMITS ONLY', 'Permits Only'), ('PENDING SUSPENSION', 'Pending Suspension'), ('PENDING EXPIRE', 'Pending Expire'), ('Out of State', 'Out Of State'), ('INVALID DATA', 'Invalid Data'), ('ID ONLY', 'Id Only'), ('EXPIRED', 'Expired'), ('CONDITIONAL', 'Conditional')], default='INVALID DATA', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licence_type',
            field=models.CharField(choices=[('C', 'C'), ('C:M', 'C M'), ('CDL_A', 'Cdl A'), ('CDL_A:M', 'Cdl A M'), ('CDL_B', 'Cdl B'), ('CDL_B:M', 'Cdl B M'), ('CDL_C', 'Cdl C'), ('CDL_C:M', 'Cdl C M'), ('D', 'D'), ('D:M', 'D M'), ('D_CONDITIONAL', 'D Conditional'), ('D_RESTRICTED', 'D Restricted'), ('E', 'E'), ('E:M', 'E M'), ('NA', 'Na'), ('OUT OF STATE', 'Out Of State'), ('PERMIT', 'Permit')], default='NA', max_length=20),
        ),
    ]
