# Generated by Django 3.2.23 on 2024-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20240516_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
